---
title: "hw2.Rmd"
output: html_document
```{r}
a0 <- 1
a0
```
#R Commands
#1
numTemp <- c(-10,15)
#fahrenheit low: -10, fahrenheit high:15
#celsius low:-23.3, celsius high:-9.4
cel <- c(-23.3, -9.4)
names(cel) <- c('low', 'high')
cel

#2
rep(c(1,0), length.out=200)
vec200 <- rep(c(1,0), length.out=200)
vec200

#3
numPerfect <- round(1,1001)
numPerfect

#Cars and Mileage
library(ggplot2)
mpg
#1
str(mpg$hwy)
sort(mpg$hwy)
a <- sort(mpg$hwy, decreasing = TRUE)
head(a, 3)
b <- head(a,3)
top3 <- b
top3

#2
sort(mpg$model)


numCompact

#3
x <- log(mpg$hwy)
y <- log(mpg$cty)
plot(x,y)
#They have a positive, linear relationship. There probably aren't many points visible because many of the numbers could be repeats or the range could be too large than what is shown

#4
hist(mpg$year)
hist(mpg$hwy)
plot(mpg$year, mpg$hwy)
#If you were to take out the outliers on the plot than yes, but with those outliers in then the answer is no. For 1999, the minimum and maximum is higher than that for 2008, so the range is higher. The range for 1999 is also larger than that of 2008.




